# Generated by Django 2.2.1 on 2019-06-27 15:19

from django.db import migrations, models
from landing.models import Property, Unit, User
from utils import factories
from django.conf import settings
import django.db.models.deletion
import timezone_field.fields


def init(apps, schema_editor):
    N_USERS = 3
    N_PROPERTIES = 3

    factories.generate_users(N_USERS)
    factories.generate_properties(N_PROPERTIES)
    prop = Property.objects.all().first()
    if prop:
        factories.populate_property(prop, 3, 10)

    unit = Unit.objects.all().first()
    user = User.objects.all().first()
    factories.generate_reservations(user, unit, 10)


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "street",
                    models.CharField(max_length=400, verbose_name="Street Name"),
                ),
                ("number", models.IntegerField()),
                (
                    "zip_code",
                    models.CharField(max_length=12, verbose_name="ZIP / Postal code"),
                ),
                ("city", models.CharField(max_length=1024, verbose_name="City")),
                ("country", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.CharField(max_length=20)),
                ("time_zone", timezone_field.fields.TimeZoneField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("occupancy", models.FloatField(default=0)),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landing.Address",
                    ),
                ),
            ],
            options={"verbose_name_plural": "properties"},
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "code",
                    models.CharField(
                        default="",
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("C", "Confirmed"),
                            ("IH", "In the unit"),
                            ("CO", "Checked out"),
                            ("CA", "Canceled"),
                            ("NS", "Didn't show up"),
                        ],
                        default="C",
                        max_length=5,
                    ),
                ),
                ("check_in", models.DateTimeField()),
                ("check_out", models.DateTimeField()),
                ("cancellation_time", models.DateTimeField(blank=True, null=True)),
                ("no_show_time", models.DateTimeField(blank=True, null=True)),
                ("adults", models.IntegerField()),
                ("children", models.IntegerField()),
                ("guest_comments", models.CharField(blank=True, max_length=400)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("currency", models.CharField(default="€", max_length=5)),
                (
                    "main_guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnitGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=200)),
                ("member_count", models.IntegerField()),
                ("max_persons", models.IntegerField()),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floors",
                        to="landing.Property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.CharField(max_length=200)),
                ("max_persons", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_occupied", models.BooleanField()),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("CL", "Clean"),
                            ("CL_TB", "Clean to be inspected"),
                            ("DR", "Dirty"),
                        ],
                        default="CL",
                        max_length=5,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="landing.Property",
                    ),
                ),
                (
                    "unit_group",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="landing.UnitGroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservationExtension",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extended_check_in", models.DateTimeField(blank=True, null=True)),
                ("extended_check_out", models.DateTimeField(blank=True, null=True)),
                ("avail_check_in", models.DateTimeField(blank=True, null=True)),
                ("avail_check_out", models.DateTimeField(blank=True, null=True)),
                (
                    "price_extension",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("currency", models.CharField(default="€", max_length=5)),
                (
                    "reservation",
                    models.OneToOneField(
                        db_column="code",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension",
                        to="landing.Reservation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reservation",
            name="unit",
            field=models.ForeignKey(
                on_delete="set_null",
                related_name="unit_reservations",
                to="landing.Unit",
            ),
        ),
        migrations.RunPython(init),
    ]
