# Generated by Django 2.2.1 on 2019-06-27 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitCleaningModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_type', models.CharField(choices=[('VIP', 'VIP'), ('FC', 'Cleaning after check-out'), ('BC', 'Cleaning without check-out')], default='FC', max_length=5)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('maintenance', models.CharField(default='', max_length=100)),
                ('personal_belongings', models.CharField(default='', max_length=100)),
                ('unit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_cleaning_model', to='landing.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_do', models.CharField(default='', max_length=50)),
                ('unit_cleaning_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_dos', to='landing.UnitCleaningModel')),
            ],
        ),
        migrations.CreateModel(
            name='Cleaner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('unit_cleaning_model', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_cleaner', to='landing.UnitCleaningModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
