# Generated by Django 2.2.1 on 2019-06-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_cleaner_todo_unitcleaningmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaner',
            name='id',
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='email',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
    ]
