# Generated by Django 2.2.1 on 2019-08-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20190627_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
